name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          # Installation des dépendances du projet
          # Exemple : npm install, pip install, etc.
          echo "Installation des dépendances du projet"

      - name: Run Tests
        run: |
          # Exécution des tests
          # Exemple : npm test, pytest, etc.
          echo "Exécution des tests"

      - name: Merge to Main
        if: github.ref == 'refs/heads/main'
        run: |
          # Fusion des modifications dans la branche principale
          git checkout main
          git merge --no-ff ${{ github.event.ref }}
          git push origin main
      
      - name: Create Release Tag
        if: github.ref == 'refs/heads/main'
        run: |
          # Création d'un tag de version
          git tag -a v${{ github.run_number }} -m "Release v${{ github.run_number }}"
          git push origin v${{ github.run_number }}

      - name: Create Pull Request
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Merge release branch into main"
          branch: main
          base: develop
          body: |
            This pull request was automatically generated to merge changes from the release branch into the main branch.
